def common_pods
#  pod 'DashSharedCore', :git => 'https://github.com/dashpay/dash-shared-core.git', :branch => 'fix/core-20-test-additional'
  pod 'DashSharedCore', :git => 'https://github.com/dashpay/dash-shared-core.git', :commit => 'a506c8560642b50dbf4e37528b8885e41cedf0db'
#  pod 'DashSharedCore', :path => '../../dash-shared-core-ferment/'
  pod 'DashSync', :path => '../'
  pod 'SDWebImage', '5.21.0'
  pod 'CocoaImageHashing', :git => 'https://github.com/ameingast/cocoaimagehashing.git', :commit => 'ad01eee'
end

abstract_target 'DashSync' do
  platform :ios, '14.0'
  common_pods
  pod 'KVO-MVVM', '0.5.1'

  target 'DashSync_Example' do
  end

  target 'DashSync_Tests' do
    inherit! :search_paths
  end
end

target 'NetworkInfo' do
  platform :osx, '10.15'
  common_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      # fixes warnings about unsupported Deployment Target in Xcode 10
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
end
