def common_pods
#  pod 'DashSharedCore', :git => 'https://github.com/dashpay/dash-shared-core.git', :branch => 'fix/core-20-test-additional'
#  pod 'DashSharedCore', :git => 'https://github.com/dashpay/dash-shared-core.git', :commit => '6426b8ab1fcce4cb0898228ca340946dfc7d5cb4'
  pod 'DashSharedCore', :path => '../../dash-shared-core/'
  pod 'DashSync', :path => '../'
  pod 'SDWebImage', '5.21.0'
  pod 'CocoaImageHashing', :git => 'https://github.com/ameingast/cocoaimagehashing.git', :commit => 'ad01eee'
end

abstract_target 'DashSync' do
  platform :ios, '14.0'
  common_pods
  pod 'KVO-MVVM', '0.5.1'

  target 'DashSync_Example' do
  end

  target 'DashSync_Tests' do
    inherit! :search_paths
  end
end

target 'NetworkInfo' do
  platform :osx, '10.15'
  common_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      # fixes warnings about unsupported Deployment Target in Xcode 10
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DASHCORE_QUORUM_VALIDATION=1'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DPP_STATE_TRANSITIONS=1'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'PLATFORM_VALUE_STD=1'
      end
    end
end
