# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'dapi-grpc-pod-installer' do
  platform :ios, '14.0'

  pod '!ProtoCompiler-gRPCPlugin', '~> 1.50.0-pre1'
  
end
