target 'dapi-grpc-pod-installer' do
  platform :ios, '14.0'

  pod '!ProtoCompiler-gRPCPlugin', '~> 1.50.0-pre1'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
