# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dapi-grpc-pod-installer' do
  platform :ios, '12.0'

  pod '!ProtoCompiler-gRPCPlugin', '~> 1.0'
  
end
